### ISSUE TITLE
weaver multi deploy runs forever even when deployment fails

### ISSUE THREAD

**Issue by itstarsun** [ServiceWeaver/weaver#104]
```sh
> weaver multi deploy weaver.toml
╭───────────────────────────────────────────────────╮
│ app        : hello                                │
│ deployment : ac742841-b8c5-44d0-bd98-807a798050d8 │
╰───────────────────────────────────────────────────╯
S0305 10:16:59.219106 stderr  0bd24c35           ] panic: listener "hello": localhost:8080 already in use
S0305 10:16:59.219231 stderr  0bd24c35           ] 
S0305 10:16:59.219239 stderr  0bd24c35           ] goroutine 1 [running]:
S0305 10:16:59.219247 stderr  0bd24c35           ] main.main()
S0305 10:16:59.219254 stderr  0bd24c35           ]      hello/main.go:18 +0xc5
S0305 10:16:59.230226 stderr  9fbaada9           ] panic: listener "hello": localhost:8080 already in use
S0305 10:16:59.230359 stderr  9fbaada9           ] 
S0305 10:16:59.230368 stderr  9fbaada9           ] goroutine 1 [running]:
S0305 10:16:59.230375 stderr  9fbaada9           ] main.main()
S0305 10:16:59.230382 stderr  9fbaada9           ]      hello/main.go:18 +0xc5
```

**Comment by spetrovic77** [comment]
Thanks for reporting, this is interesting. Right now, Ctrl+C will kill the `weaver multi` process (and all others), but you're saying that it should kill itself automatically whenever one of the underlying component processes fail?

It's tricky because `weaver multi` actually runs multiple replicas of all of its processes. This is to help test the cloud"scenario where processes/containers are replicated. We likely don't want to kill the whole application if one process fails, and we actually attempt to restart all crashed processes on failure. (And repeatedly do so as long as they keep crashing.) Again, this is to simulate the cloud scenario where the containers get restarted automatically on failure.

So I believe we don't want to implement the behavior of killing the whole app whenever a process fails.
