### ISSUE TITLE
Is it a bug when counting procs in the colocation group?

### ISSUE THREAD

**Issue by collinmsn** [ServiceWeaver/weaver#125]
```
// numProcsIn returns the number of processes assigned to the provided group,
// using the placement specified in the provided set of components.
func numProcsIn(group *protos.ColocationGroup, components map[string]*component) int {
	procs := map[string]bool{}
	for _, c := range components {
		if c.colocGroupName == group.Name {
			procs[c.processName] = true  
		}
	}
	return len(procs)
}
```

In the Place function, components are divided into group，and components in the same group get there processName set to the first component's component name。So in func numProcsIn, len(procs) can never be > 1

**Comment by mwhittaker** [comment]
Hi @collinmsn. Good find! You're absolutely right that, currently, `numProcsIn` will always return 0 or 1. In earlier versions of the code, we allowed multiple different processes to be co-located together, with communication between them done via shared memory. We disabled this feature for now but may introduce it again later. When this feature was enabled, `numProcsIn` made a lot more sense and could return a value greater than 1. 

I'll close this issue for now since there's no bug, but we are actively working on cleaning up this code. Thanks for bringing it to our attention!
