### ISSUE TITLE
Synchronized component implementation (feature idea)

### ISSUE THREAD

**Issue by diegofrata** [ServiceWeaver/weaver#540]
Apologies if this has been suggested / discussed elsewhere -- I did search but did not find anything. I attended the workshop this evening and it was quite fun to play with weaver. One thing that I have to do repeatedly in services that are accessed via network or via multiple goroutines is ensuring access is synchronized. A lot of times I will write something like this (borrowing from the workshop cache example):

```
func (c *cache) Put(ctx context.Context, key string, value []string) error {
	c.mu.Lock()
	defer c.mu.Unlock()

	c.storage[key] = value
	return nil
}
```

The first thing that came to mind is that perhaps this could be handled in the stub with the help of the code generator.  For example, if the goal is for the implementation to be sync, the user could use `weaver.SyncImplements` instead of `weaver.Implements`.

```
type cache struct {
	weaver.SyncImplements[Cache]
}
```

Thoughts? I could try submit a PR if there's interest in this feature.

**Comment by mwhittaker** [comment]
Hi @diegofrata! If I understand correctly, the benefit of `SyncImplements` is that it saves a programmer the effort of adding a `sync.Mutex` field to their implementation struct and adding two lines to every method (one to `Lock` and one to `Unlock`). 

I think it's an interesting idea, but I worry that this is not a big enough benefit to compensate for some of the drawbacks of the proposal. For example, the approach does not generalize well. If someone needs an [`RWMutex`](https://pkg.go.dev/sync#RWMutex) instead of a `sync.Mutex`, they can't use `SyncImplements`. Or, if they need access to the mutex to initialize a `sync.Cond`. Or, if some methods don't need to be locked, or don't need to be locked for the duration of the method. 

There are also some aspects of the API we would have to sort out and explain to users, which brings complexity. For example, is the mutex acquired in all methods of the struct, or only those that are part of the component interface it implements? If it's all methods, then how do methods call each other without deadlocking? And if it's only the methods in the interface, then what do I do if I need to lock another method? And what about methods the struct may inherit from embeddings? 

I think if the redundancy or complexity of the existing approach was higher or if there were a natural and general way to solve the problem, I would be in favor. But as is, I would prefer to leave things as is.

**Comment by diegofrata** [comment]
Hi @mwhittaker,

Reading your comments made me rethink whether my proposal would be at all that useful. But to answer your questions, what I imagined is simply a standard mutex on the stub (or use channels to queue the calls and turn it into a message box essentially). Users already have the freedom to work out more intricate solutions if they want to -- what is missing is a easy way to synchronize a component that will be useful most of the time.

When I first thought of `SyncImplements`, I thought of the example of the cache where, while not optimal (i.e. using RWLock) it provides a safe starting point for developers. However, the more I think about it the clearer it is how much of an outlier the Cache example is. 

If I swap the example from cache to some sort of banking transaction, then the `SyncImplements` is actually harmful, as you'd not want to serialize deposits across multiple accounts -- you might want to serialize the access to the map or something, but not the actual operation on account. So if I was writing a bank account service, I would write something like the below.

```
package main

import (
	"context"
	"sync"

	"github.com/ServiceWeaver/weaver"
)

type BankAccountService interface {
	Deposit(ctx context.Context, accountNumber string, amount float64) error
}

type bankAccountService struct {
	weaver.Implements[BankAccountService]
	mu       sync.Mutex
	accounts map[string]*bankAccount
}

func (b *bankAccountService) getAccount(accountNumber string) *bankAccount {
	b.mu.Lock()
	defer b.mu.Unlock()

	if account, ok := b.accounts[accountNumber]; ok {
		return account
	}

	account := &bankAccount{}
	b.accounts[accountNumber] = account
	return account
}

func (b *bankAccountService) Deposit(ctx context.Context, accountNumber string, amount float64) error {
	account := b.getAccount(accountNumber)

        // If SyncImplements was used in this service, then this call would be serialized, 
        // which could kill the throughput of the system.
	account.Deposit(amount)
	return nil
}

func (b *bankAccountService) Init(ctx context.Context) error {
	b.accounts = make(map[string]*bankAccount)
	return nil
}
```
`SyncImplements` would be actually useful is on the bankAccount itself, as you'd never want Deposits and Withdrawals to happen concurrent and bank accounts don't need fine grained contention management -- essentially you'd always be happy with a standard mutex. Correct me if I am wrong here, but the bank account would never be a weaveable service because there isn't a thing such as named services or entities, so it couldn't benefit from `SyncImplements`, right?

```
type bankAccount struct {
	mu      sync.Mutex
	balance float64
}

func (b *bankAccount) Deposit(amount float64) {
	b.mu.Lock()
	defer b.mu.Unlock()

	b.balance += amount
}
```

So, after thinking about it, feels like my proposal would only be useful if you could distribute entities as you distribute services -- but that would be branching into actor models territory and it doesn't feel like a it's a goal of Service Weaver.

**Comment by mwhittaker** [comment]
> Correct me if I am wrong here, but the bank account would never be a weaveable service because there isn't a thing such as named services or entities, so it couldn't benefit from SyncImplements, right?

**Comment by diegofrata** [comment]
I will close this issue as it is obviously a non-runner. Thanks for entertaining it!
