### ISSUE TITLE
Probably useless generics parameter

### ISSUE THREAD

**Issue by Duslia** [ServiceWeaver/weaver#703]
I looked at the generic parameters of the Run function and felt that the definition of P was unnecessary. After I removed P, the code still runs normally, which makes me feel that the generic parameter here is redundant.

https://github.com/ServiceWeaver/weaver/blob/7ba5ecdd150cf9c349d3a3dc2a698a1d8d3e35a7/weaver.go#L133

**Comment by mwhittaker** [comment]
Hi @Duslia! This code is pretty confusing :dizzy_face:! 

Without the `PointerToMain[T]` constraint, it is possible to call `Run[T]` with a `T` that is not a main component. This should cause the code to crash at runtime, when it instantiates a `T` expecting `T` to be a main component: 

https://github.com/ServiceWeaver/weaver/blob/7ba5ecdd150cf9c349d3a3dc2a698a1d8d3e35a7/weaver.go#L177

The `PointerToMain[T]` constraint makes this error a compile time error rather than a crash at runtime. If you remove the constraint, the current code should compile and run correctly.
