### ISSUE TITLE
ssh deploy and firecracker

### ISSUE THREAD

**Issue by gedw99** [ServiceWeaver/weaver#725]
there is a easy way to run firecracker with weaver ssh deploy.

docs: https://docs.nats.io/using-nats/nex
code: https://github.com/synadia-io/nex

This gives you a cloud in a box in many ways. 

When you mix weaver with NATS you can orchestrate your "cloud".

I just adding this as an Issue even though its not an issue because the 2 things works so well together IMHO.  

The SSH deployer is missing a few things are documented here: https://serviceweaver.dev/docs.html#ssh-experimental-limitations

The NATS Cli can be used to control Weaver, so I might make a "weaver nats deploy" etc ...

Am just thinking out loud here to see if anyone is into this. Would appreciate any feedback about this concept / approach.

**Comment by ripienaar** [comment]
1. `nats` is pluggable so you could also have `nats weaver` if you really wanted, ping me if you're curious
2. Your basic nats context usage is really just `natscontext.Connect(os.GetEnv("NATS"), opts)` that's all.  Our integrations in cli is more complex because we also want to support passing/overriding some flags from command line, most people wont need that, simple one liner is enough.

**Comment by gedw99** [comment]
hey @ripienaar 

yep a NATS weaver is exactly what I am working on. SO you can just connect over the NATS control plane.   I dont know how to reach you :) I am on Telegram though...

**Comment by gedw99** [comment]
Hey @ripienaar 

If you have time for a chat about this can you grab me on telegram or suggest what you want to use ?

**Comment by ripienaar** [comment]
Slack is where nats support happens.
