### ISSUE TITLE
Handling DB cleanup correctly

### ISSUE THREAD

**Issue by Galaf** [ServiceWeaver/weaver#765]
Hello!

Thanks for your good work!

I was wondering what would be the best practice to handle DB (or otherwise) cleanup.
Components offer a way to do `Init()` but there is no hook for deinitialization, therefore I don't know how best to express something like that:

```go
client, err := ent.Open("driver", "host")
// err validation
defer client.Close() // <-- this.
```

I'm thinking that perhaps before serving the app, I could create a global variable and wait for the shutdown signal in a goroutine to do this but I'd like to have your opinion on this subject, if possible!

Thanks a lot for your time!

**Comment by renanbastos93** [comment]
Hi dude, I believe that your pain is valid to implement a new method like Init but with Shutdown. Even though not solve for whole your pain it will rather than. Well, I don't like using global variables. I'd make methods in my app to CloseDB(), which will call when you shut down your main `Run` method. 

See below:
```go
func Serve(ctx context.Context, e *implBFF) error {
	fmt.Printf("BFF listener available on %v\n", e.bff.String())

	f := fiber.New()

	e.createRouter(ctx, f)

	defer func(){
		e.db.Close()
	}()

	return f.Listener(e.bff)
}
```

@rgrandl What do you think of us implementing a `Close(ctx) error` method, like `Init(ctx) error`?

**Comment by Galaf** [comment]
Yes, I thought about that but it beats the purpose of using `Init(ctx)` in the first place if I initialize everything in `main()`, I believe :)

**Comment by Galaf** [comment]
Similar to: https://github.com/ServiceWeaver/weaver/issues/275

**Comment by rgrandl** [comment]
I created #766 to add a `Shutdown` method.

**Comment by rgrandl** [comment]
If you install the latest weaver version (v0.24.2) you should be able to add a `Shutdown` command to your application as mentioned in https://serviceweaver.dev/docs.html#components-interfaces.
